language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: XdXM0R15zV5V3mfegOkh9IJuWaOMr6Sfi8UGtNIaKv1c0dZbj35HXPnnviyLZQxlLc05EHij1ijWpsd4gyVRo2dt8zsZYQVouofRe62ZuzkZkqyYdY+zAZ9cWdMP5DoaiV++XwUZV/CswhM8HuUr+kPHZWV4UZrRCKP3By6VQuw=
  - secure: MkzCxrMfSI5iQdKIXnQAqmmLG1XX2M6mtvR+5+O83LprKhmuu5PCE6xS+YacsNwbsK/igkTmokmquTSI5ZFPQGKwC3NQl4LEYq2T0Tat4u5qsjp8p13zP2uVjfj9rtDgGoxjt0qZ21CLT5m+5kJkug9cVkmtirDz9eO11MhTjCw=
